### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by TDogOh9** [net-lisias-ksp/KSPe#61] opened 2023-10-12 14:34 UTC
[KSP.log](https://github.com/net-lisias-ksp/KSPe/files/12883659/KSP.log)

i installed a mod from curseforage named skillful weapons and damage 1.0.5 and it happened but i didnt before

**Comment by Lisias** [comment] 2023-10-12 22:50
@TDogOh9 ,

> i installed a mod from curseforage named skillful weapons and damage 1.0.5 and it happened but i didnt before

What's happening is that KSP is being "patched" remotely by Squad, changing  some internal behaviours that were used to detect problems. It's essentially the same problem described on #59.

Besides that, now some problems are silently ignored, making diagnosing difficult.

So, the problem now is KSP, not TweakScale. You will probably have to uninstall `IDSkillfulR1` because it's old age DLL probably is failing to being loaded. I installed it on my rig, and I found this:

```
[LOG 19:48:56.468] PartLoader: Compiling Part 'IDSkillfulR1/Parts/ArmourAirBPlate/part/IDArmourAirBPlate'
[LOG 19:48:56.519] EffectList: Created 15 effect types
[EXC 19:48:56.617] CustomAttributeFormatException: Could not find a field with name guiName
        System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeTyp
        System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, S
        System.Reflection.MonoMethod.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) (at <9577ac7a62ef43
        BaseEventList+ReflectedData..ctor (System.Type type) (at <106570632fc343a784fad39e75e877bf>:0)
        BaseEventList.GetReflectedAttributes (System.Type type) (at <106570632fc343a784fad39e75e877bf>:0)
        BaseEventList.CreateDelegates (System.Object part) (at <106570632fc343a784fad39e75e877bf>:0)
        BaseEventList..ctor (Part part, PartModule module) (at <106570632fc343a784fad39e75e877bf>:0)
        PartModule.ModularSetup () (at <106570632fc343a784fad39e75e877bf>:0)
        PartModule.Awake () (at <106570632fc343a784fad39e75e877bf>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.GameObject:AddComponent(Type)
        Part:AddModule(String, Boolean)
        Part:AddModule(ConfigNode, Boolean)
        PartLoader:ParsePart(UrlConfig, ConfigNode)
        <CompileParts>d__56:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        <CompileAll>d__13:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        PartLoader:StartLoad()
        <LoadSystems>d__11:MoveNext()
        UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

So these parts are unusable anyway.

**Comment by Lisias** [comment] 2023-10-12 22:55
As a matter of fact, on my rig I got the following message when trying to load a savegame after installing `IDSkillfulR1`:

![Screen Shot 2023-10-12 at 19 52 10](https://github.com/net-lisias-ksp/KSPe/assets/64334/18ec9ccc-f8b9-452c-a5c4-54cfcb82f7e3)

I'm considering these new changes deleterious.

**Comment by Lisias** [comment] 2024-03-24 16:09
It's more than due time to get rid of this one. Check it again before the designed milestone.

**Comment by Lisias** [comment] 2024-03-29 18:55
There's nothing I can do. The mentioned addon is just broken beyound salvage:

```
[LOG 09:25:37.742] Load(Assembly): WarpPrimeWeaponry/Plugins/WarpPrimeWeaponry
[LOG 09:25:37.742] AssemblyLoader: Loading assembly at C:\Program Files\Epic Games\KerbalSpaceProgram\English\GameData\WarpPrimeWeaponry\Pl
ugins\WarpPrimeWeaponry.dll
[LOG 09:25:37.745] AssemblyLoader: Loading assemblies
[ERR 09:25:37.819] ADDON BINDER: Cannot resolve assembly: EVEManager, Culture=neutral, PublicKeyToken=null

[ERR 09:25:37.819] ADDON BINDER: Cannot resolve assembly: EVEManager, Culture=neutral, PublicKeyToken=null

[ERR 09:25:37.820] ADDON BINDER: Cannot resolve assembly: Utils, Culture=neutral, PublicKeyToken=null

[ERR 09:25:37.820] ADDON BINDER: Cannot resolve assembly: Utils, Culture=neutral, PublicKeyToken=null
```

Not to mention:

```
[EXC 09:25:38.849] NotSupportedException: The invoked member is not supported in a dynamic module.
    System.Reflection.Emit.AssemblyBuilder.get_Location () (at <9577ac7a62ef43179789031239ba8798>:0)
    _BuildManager._BuildManager+<>c__DisplayClass2_0.<logVersion>b__0 (System.Reflection.Assembly x) (at <5329a27ec3b64178b009f7e4fdd9f215>:0)
    System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
    System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
    _BuildManager._BuildManager.logVersion () (at <5329a27ec3b64178b009f7e4fdd9f215>:0)
    _BuildManager._BuildManager.Awake () (at <5329a27ec3b64178b009f7e4fdd9f215>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
    UnityEngine.GameObject:AddComponent(Type)
    AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
    AddonLoader:StartAddons(Startup)
    <LoadObjects>d__90:MoveNext()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    <CreateDatabase>d__71:MoveNext()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    GameDatabase:StartLoad()
    <LoadSystems>d__11:MoveNext()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    LoadingScreen:Start()
```

It's really game over by now (both due the time I took to check this again, as well the problem is beyound me). So I'm closing this.

**Closed by Lisias** 2024-03-29 18:55 UTC
Labels: support
